// File generated by FlutLab.
// Importing necessary packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  // Getter to provide the Firebase options based on the platform
  static FirebaseOptions get currentPlatform => android;

  // Firebase options for the Android platform
  static const FirebaseOptions android = FirebaseOptions(
    apiKey:
        'AIzaSyBxkSBaVgaUHZKTpm70O6xUu6kBQxm6dkI', // Replace with your API Key
    appId:
        '1:405752215647:android:388d34c05056faf62703ea', // Replace with your App ID
    messagingSenderId: '405752215647', // Replace with your Messaging Sender ID
    projectId: 'artic-7d7ff', // Replace with your Project ID
    storageBucket:
        'artic-7d7ff.appspot.com', // Replace with your Storage Bucket
  );
}
